[package]
name = "bitcoin-adddress-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256k1 = "0.27.0"
rand = "0.8.4"
itertools = "0.10.1"